### ISSUE TITLE
crash when click on graph

### ISSUE THREAD

**Issue by muhammadarif1** [leeranzhi/AccountingApp#1]
android 5.1
```FATAL EXCEPTION: main
Process: com.leecode1988.accountingapp, PID: 4600
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.leecode1988.accountingapp/com.leecode1988.accountingapp.activity.AnnualStatisticsActivity}: java.lang.NumberFormatException: Invalid double: "-31386,00"
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2525)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617)
	at android.app.ActivityThread.access$800(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
Caused by: java.lang.NumberFormatException: Invalid double: "-31386,00"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:164)
	at java.lang.StringToReal.parseDouble(StringToReal.java:282)
	at java.lang.Double.parseDouble(Double.java:301)
	at java.lang.Double.valueOf(Double.java:338)
	at com.leecode1988.accountingapp.activity.AnnualStatisticsActivity.initView(AnnualStatisticsActivity.java:101)
	at com.leecode1988.accountingapp.activity.AnnualStatisticsActivity.onCreate(AnnualStatisticsActivity.java:61)
	at android.app.Activity.performCreate(Activity.java:6135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2472)
	... 10 more```

**Comment by muhammadarif1** [comment]
please feedback sir

**Comment by leeranzhi** [comment]
> please feedback sir

I am very sorry, I have not paid attention to the updates of Issues.
Thanks for your feedback, and the Crash log submitted; after troubleshooting, I have solved this Crash,
It is due to the error in localizing the decimal point during the amount conversion process.

From Wikipedia:
A decimal mark is a symbol used to separate the integer part from the fractional part of a number written in decimal form. 
Different countries officially designate different symbols for the decimal mark. The choice of symbol for the decimal mark also affects the choice of symbol for the thousands separator used in digit grouping, so the latter is also treated in this article.

**Comment by leeranzhi** [comment]
> please feedback sir

I am very **sorry**, I have not paid attention to the updates of Issues.
Thanks for your feedback, and the Crash log submitted; after troubleshooting, I have solved this Crash,
It is due to the error in localizing the decimal point during the amount conversion process.

**From Wikipedia:**
A decimal mark is a symbol used to separate the integer part from the fractional part of a number written in decimal form.
Different countries officially designate different symbols for the decimal mark. The choice of symbol for the decimal mark also affects the choice of symbol for the thousands separator used in digit grouping, so the latter is also treated in this article.

**Comment by leeranzhi** [comment]
> please feedback sir

I am very **sorry**, I have not paid attention to the updates of Issues.
**Thanks** for your **feedback**, and the Crash log submitted; after troubleshooting, I have solved this Crash,
It is due to the error in **localizing** the decimal point during the amount conversion process.

**From Wikipedia:**

> A decimal mark is a symbol used to separate the integer part from the fractional part of a number written in decimal form.
> Different countries officially designate different symbols for the decimal mark. The choice of symbol for the decimal mark also affects the choice of symbol for the thousands separator used in digit grouping, so the latter is also treated in this article.

**Comment by leeranzhi** [comment]
> > please feedback sir
> 
> I am very **sorry**, I have not paid attention to the updates of Issues.
> **Thanks** for your **feedback**, and the Crash log submitted; after troubleshooting, I have solved this Crash,
> It is due to the error in **localizing** the decimal point during the amount conversion process.
> 
> **From Wikipedia:**
> 
> > A decimal mark is a symbol used to separate the integer part from the fractional part of a number written in decimal form.
> > Different countries officially designate different symbols for the decimal mark. The choice of symbol for the decimal mark also affects the choice of symbol for the thousands separator used in digit grouping, so the latter is also treated in this article.
